CMS_HOST: studio.mohit.io
CMS_OAUTH2_SECRET: cxRzljq6yNOZWhOYVqQHpM2N
CONTACT_EMAIL: contact@mohit.io
ENABLE_HTTPS: true
ID: bSdUn0tQ97icYISJMRR8T3Cl
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEAteg2M9w/8t5U6sORLxztLQbw0YBHVao/VvFyemIFzfsdT7kx

  fw+v1HU/7PSjoEkibO0gJwwMyVQddFkT3X41H6ARAeGayXY4P2t9PLSvRV/UHC3a

  uBlZ205Y3qiI6j9bC0wUSvsqXurSOPYiHmSI95eUie51UQXzr8TSCJds2IaZ/CET

  /QmDS2o81Sz2zSMq8HUEJ/YgqwNwGeMZyJn+rPb0/P3bSu88MvEc2Jj2TprwPs3B

  C18m0QKT8gy0plbqA8tN25WqFS0TCRgye69VD8Gxqmbw4Rlor2CzzUHWAhTq3tfb

  nlQ++VN48yIhUAv4GSNv+8CNo896ORkQudPKBwIDAQABAoIBAEHr4yisGqijFdb2

  BHk0XGdC6qahfDh5N/cEDN55A22AIUEw9dT8FFZEH2R5y4pctpMO4+YCoeecCgiN

  93r/L7VERqWN4pA7vWqOQ5ZqTFIxxiZoH6kz1rJ5FA+st+FcEFxpt7jsiJBZPNHT

  sM2e1VwUnInX1sAEDimWhB8E8TcOA6cx2IZvHRb7NZsKDu5/XrUtjLzXQiTtEyK8

  FPXDFgysbaExNsZ1IEPSf2zp87DGWw8jXdDLeQAmu7gSRb9E50bkPSsVL07uiQCV

  6o0AVuKOVirCnVmo5VeRz26sd3AbJQC5QauGGmdc/EYUTWBVUdpSQcKdvpcrk/Tz

  6+FvoIECgYEAykGlPVN/9/31ByOAJjvwV7SQC2ZHvJKnQszmMj+KJSj0zbJsrvWZ

  VRU8EWHmZH5jS7WOyZnCY62DwBHBY3E/F2vgbVBiU7X4R6v3siJ5pfJGXSR3MQny

  29UAfIeP088gz+Ks1tM6mnHmmlvTFggBbVR+nFG3VVrVJ6tloXTSoicCgYEA5j5Q

  z95WIjp2TYjODqtjXEsL/g47vElZF/BcsH/xQtQcxjLYJGHMDcfa/qokMdnwgOKD

  OusTw5htpbvL+gg+4TC5nd9b1yhSTs/OGEdUIAETrAlSzoS15j+kdRhWsCpCac1X

  bHp54L73CbeIF5WIyHiADFSbf6zJ/8P2pKdg5SECgYB8BQjHs/3SGR04hWI9D5/u

  h7+T3eG7FcoOQgodYazZ4GVMBE50chDVhTHSDs/xazaD5A5sPCZgbLNPARQuX/Cp

  8fIp1ZKVdg2KFT7LMiyZvxe6YXPc1BbhCZlEwvNEk8uw7XPCPr++mH0oxYmIBtyp

  J5iDTfA3HH1717N372SBHQKBgBtN8I92MojEnhr7ylP7B0F+tOFgFr1xhVtNafCU

  e6wNM4xdozxNTMGlndbtnnU6/0aJlj56elGL1hT9fGceazaRbLHIN0AAzCIEitBe

  RR+2gPq58FQFcPzpNzubs0wY9t9NNrzqmWGJxAom9cC2Pw5nG+hacEZn21y1hJ5q

  KxeBAoGAPoAf0AdF86lTkdPsvdoIG2MrKG80BfaE1CnO1bacQznZfVCkTOASL2Go

  S1oX9SdQjHYPwVVl+/6VwOyncvj68E+e0L84IrLrbXGezDrj9JhwPILeEAIN0DUI

  QeMrHBLCJ4uAAeqpu0P7JF4Vw5Dm7a6Ngy09C99GhknAozmVfC4=

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: mohit.io
MYSQL_ROOT_PASSWORD: uzZfqbIa
OPENEDX_MYSQL_PASSWORD: Bl1HXkcn
OPENEDX_SECRET_KEY: YpmIcnCkQwJzVjAHsiX2sGdD
PLATFORM_NAME: My Open edX
PLUGINS:
- forum
- mfe
